version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins_container
    ports:
      - "9099:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_OPTS: --httpPort=8080
    restart: unless-stopped


volumes:
  jenkins_home: